FROM node:lts-alpine as builder

WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

ARG VITE_API_URL=http://103.116.9.29:3000/api
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build

FROM nginx:stable-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html