version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass abc
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  database:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=EVENTS_AROUND
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  backend:
    container_name: backend
    depends_on:
      - redis
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=mysql://root:123123@database:3306/EVENTS_AROUND
      - CLIENT_URL=http://localhost:5173
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=abc
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - 5173:5173

volumes:
  db:
  redis:
