export const categories = [
  { name: 'Concerts' },
  { name: 'Conferences' },
  { name: 'Workshops' },
  { name: 'Sports' },
  { name: 'Art Exhibitions' },
  { name: 'Networking Events' },
  { name: 'Charity Events' },
  { name: 'Food & Drink' },
  { name: 'Technology' },
  { name: 'Family & Kids' },
  { name: 'Film & Cinema' },
  { name: 'Fashion & Beauty' },
  { name: 'Health & Wellness' },
  { name: 'Music Festivals' },
  { name: 'Theater & Drama' },
  { name: 'Literary Events' },
  { name: 'Comedy Shows' },
  { name: 'Educational' },
  { name: 'Business' },
  { name: 'Outdoor & Adventure' },
  { name: 'Science & Technology' },
  { name: 'Gaming' },
  { name: 'Holiday & Seasonal' },
  { name: 'Travel & Tourism' },
  { name: 'Cultural' },
  { name: 'Dance' },
  { name: 'Photography' },
  { name: 'Hobbies & Crafts' },
  { name: 'Cars & Automobiles' },
  { name: 'Pets & Animals' },
  { name: 'Virtual Events' },
  { name: 'Expos & Trade Shows' },
  { name: 'Gala & Fundraisers' },
  { name: 'Weddings & Bridal' },
  { name: 'Yoga & Meditation' },
  { name: 'Fitness & Exercise' },
  { name: 'Seminars' },
  { name: 'Political Events' },
  { name: 'Fashion Shows' },
  { name: 'Home & Garden' },
  { name: 'Art & Crafts' },
  { name: 'Wine & Spirits' },
];
